### ISSUE TITLE
Integrate into Wagtail

### ISSUE THREAD

**Issue by fabienheureux** [bbmokhtari/django-translations#55]
Hey, this is more an advice's request rather than a feature request. 

I am currently trying to integrate your project into a Wagtail project (http://github.com/wagtail/wagtail).  
Wagtail uses a different admin than django-admin, so it is not straightforward. 

I was wondering if you could lead me to some general concepts regarding your project that could help me build a custom admin in Wagtail based on it. 

By the way, thanks a lot for your work, it is very well documented.

**Comment by bbmokhtari** [comment]
Hey there.

If the wagtail project is extending the Django admin then this topic in the documentation may help you: *How to: Integrate with custom admins*. You can find it in the main page of the documentation or in the *How to* category.

If it doesn't extend the Django admin and it's using custom views for its admin page then you might have to find a way to override the views you want so that you can alter the QuerySet in it with translation capabilities.

Btw you're welcome!

**Comment by fabienheureux** [comment]
Thanks for your answer, in fact, it does not implement Django admin but a completely custom admin. 
Their admin is quite extendable though, so I will look into this direction.
